export const FETCH_ALL_IMAGES = "FETCH_ALL_IMAGES";
export const FETCH_IMAGES_BY_TAG = "FETCH_IMAGES_BY_TAG";
export const FETCH_IMAGES_BY_SEARCH = "FETCH_IMAGES_BY_SEARCH";
export const FETCH_IMAGE_BY_ID = "FETCH_IMAGE_BY_ID";
export const UPDATE_IMAGE_TAG = "UPDATE_IMAGE_TAG";
export const UPDATE_IMAGE_ID = "UPDATE_IMAGE_ID";
