
// synchronous
export const SELECT_MODE = 'SELECT_MODE';
export const SELECT_FILTER_MODE = 'SELECT_FILTER_MODE';
export const SELECT_PRIMARY_IMAGE = 'SELECT_IMAGE';
export const SELECT_ASSOC_IMAGE = 'SELECT_ASSOC_IMAGE';
export const SORT_GALLERY = 'SORT_GALLERY';

// asynchronous
export const FETCH_GALLERY = 'FETCH_GALLERY';
export const FETCH_ASSOC_IMAGES = 'FETCH_ASSOC_IMAGES';
export const FETCH_PRODUCT_LIST = 'FETCH_PRODUCT_LIST';
